apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi-deployment
  labels:
    app: basketapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketapi
  template:
    metadata:
      labels:
        app: basketapi
    spec:
      containers:
        - name: basketapi
          image: riannegreiros/ecommercemicroservicesbasketapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: CacheSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: redis-configmap
                    key: connection_string
            - name: GrpcSettings__DiscountUrl
              valueFrom:
                configMapKeyRef:
                  name: basketapi-configmap
                  key: discount_url
            - name: EventBusSettings__HostAddress
              valueFrom:
                configMapKeyRef:
                  name: basketapi-configmap
                  key: host_address
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: basketapi-service
spec:
  type: NodePort
  selector:
    app: basketapi
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 31000