apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountapi-deployment
  labels:
    app: discountapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountapi
  template:
    metadata:
      labels:
        app: discountapi
    spec:
      containers:
        - name: discountapi
          image: riannegreiros/ecommercemicroservicediscountapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: postgres-configmap
                    key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discountapi-service
spec:
  type: NodePort
  selector:
    app: discountapi
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 80
      nodePort: 32300